version: "3.9"
services:
  postgresdb:
    image: postgres:15.1
    platform: linux/amd64
    container_name: postgres-for-goose-test
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
volumes:
  pg_data:

